// Code generated by templ@v0.2.316 DO NOT EDIT.

package widgets

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"fmt"
)

func Counter(count int) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<form hx-post=\"/counter\" hx-swap=\"outerHTML\" class=\"flex flex-col\" hx-ext=\"disable-element\" hx-disable-element=\"#count-submit\"><input type=\"hidden\" name=\"count\" value=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprint(count)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\"><button id=\"count-submit\" type=\"submit\" class=\"btn btn-primary\"><span class=\"loading loading-spinner htmx-indicator\"></span> ")
		if err != nil {
			return err
		}
		var_2 := `Click Me `
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		var var_3 string = fmt.Sprint(count)
		_, err = templBuffer.WriteString(templ.EscapeString(var_3))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button>")
		if err != nil {
			return err
		}
		if count > 0 {
			_, err = templBuffer.WriteString("<p>")
			if err != nil {
				return err
			}
			var_4 := `You did it, good job 🎉`
			_, err = templBuffer.WriteString(var_4)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</p> <p>")
			if err != nil {
				return err
			}
			var_5 := `No javascript here! Check the network tab.`
			_, err = templBuffer.WriteString(var_5)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</p>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</form>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = io.Copy(w, templBuffer)
		}
		return err
	})
}
